### ISSUE TITLE
UGS Freeze/Stops

### ISSUE THREAD

**Issue by stereolab54** [winder/ugs_website#10]
I have a recent issue of UGS freezing midway through CNC jobs.  The issue is unpredictable despite having updated the Xms value from 64 to 256 as well as changing my Windows power settings to never shut off.  I'm using version 2.0 from a nightly build dated 6/3/18.  I have also used UGS stable version 2.0 and have the same issue.  Has anyone else experience this?

First time posting so apologies in advance if this question should be posted elsewhere.

**Comment by breiler** [comment]
Please post your question on https://github.com/winder/Universal-G-Code-Sender

**Comment by jratha** [comment]
I’ve had the same issues. If I’m doing complex jobs that  take more than an hour, I’ve had to revert to using the openbuilds platform. Anything less than an hour or probing , I’m still using UGS and waiting for an update

**Comment by stereolab54** [comment]
Thank you breiler and jratha.  I've posted the question on the link provided.
