### ISSUE TITLE
UGS wont launch on RPI

### ISSUE THREAD

**Issue by jratha** [winder/ugs_website#5]
HI

Not sure if this has been sorted yet or if there is a solution already in the pipeline, but Im trying to setup a pi to run my cnc. Ive always used ugs, i can set everything up fine, cloned ugs, set up maven but ugs refuses to launch.

Any help would be apreciated

**Comment by winder** [comment]
This is the UGS documentation repository, you'll need to post this here: https://github.com/winder/Universal-G-Code-Sender/issues
